# CS 225 Lab 02
# Written by Jack Toole Fall 2010

CXX = clang++
CXXFLAGS = -std=c++1y -stdlib=libc++ -w
LDFLAGS = -std=c++1y -stdlib=libc++ -lc++abi -lpthread
TESTOBJS = rgbapixel.o png.o sketchify.o
include Makefile.proxy

